### ISSUE TITLE
Конфликт с Laravel 8

### ISSUE THREAD

**Issue by Lezhni** [ElForastero/Transliterate#16]
Библиотека конфликтует с Laravel 8:
`elforastero/transliterate 4.0.0 requires illuminate/support ^6.0|^7.0`

**Comment by ElForastero** [comment]
Да, нужно обновить range зависимостей на >= везде.

Попробую сегодня залить апдейт.

**Comment by gluktd** [comment]
> Да, нужно обновить range зависимостей на >= везде.
> 
> Попробую сегодня залить апдейт.

Плиз ду)) Спасёшь зе вордл)

**Comment by lycifer3** [comment]
Очень жду фикс

**Comment by ElForastero** [comment]
@Lezhni @gluktd @lycifer3 Опубликовал RC с поддержкой Laravel 8.

Можете проверить все ли ок у вас?

```bash
composer require elforastero/transliterate @RC
```

Если все нормально, опубликуем релизную версию.

**Comment by lycifer3** [comment]
@ElForastero получается вот как
Installation failed, reverting ./composer.json and ./composer.lock to their original content.

In ClassLoader.php line 476:
                                                                                                                                                   
  include(/app/vendor/composer/../composer/composer/src/Composer/Console/GithubActionError.php): failed to open stream: No such file or directory

**Comment by ElForastero** [comment]
@lycifer3  Это что-то не связанное с пакетом. Ошибка локально или в пайплайне? Выглядит как в пайплайне каком-то.

Попробуй ради интереса `composer dumpautoload`.

**Comment by lycifer3** [comment]
@ElForastero Да, помогло, все работает.

**Comment by Lezhni** [comment]
@ElForastero таки да, у меня тоже норм
